### ISSUE TITLE
Cannot use nifty from channel cpape currently

### ISSUE THREAD

**Issue by hanslovsky** [constantinpape/interactive_solver_backend#1]
```shell
python -c 'import nifty.graph.rag as nrag'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hanslovskyp/miniconda3/envs/agglomerate/lib/python3.6/site-packages/nifty/graph/rag/__init__.py", line 7, in <module>
    from . import _rag as __rag
ImportError: libfastfilters.so.0.2.5-9-geb270d2: cannot open shared object file: No such file or directory
```
I cannot find an appropriate `libfastfilters` version on `ilastik-forge`. Which branch of `nifty` do I need to build?
Can I just use nifty from `ilastik-forge`?

**Comment by hanslovsky** [comment]
I tested nifty from `ilastik-forge` and it did not work. I figure I need to build the `stacked_rag` branch. Trying to to that right now. Any chance, that branch will be merged into master at some point?

**Comment by hanslovsky** [comment]
What options do I need?
Unfortunately, the build fails with
```
 WITH_CPLEX                       OFF                                                                                                                                                                                                                                                                                      
 WITH_FASTFILTERS                 ON                                                                                                                                                                                                                                                                                       
 WITH_GLPK                        ON                                                                                                                                                                                                                                                                                       
 WITH_GUROBI                      OFF                                                                                                                                                                                                                                                                                      
 WITH_HDF5                        ON                                                                                                                                                                                                                                                                                       
 WITH_LP_MP                       ON                                                                                                                                                                                                                                                                                       
 WITH_QPBO                        ON 
```

```
[ 42%] Building CXX object src/python/lib/graph/opt/multicut/CMakeFiles/_multicut.dir/multicut_mp.cxx.o
In file included from /home/hanslovskyp/workespace-intellij/paintera/nifty/externals/LP_MP/include/visitors/standard_visitor.hxx:4,
                 from /home/hanslovskyp/miniconda3/envs/agglomerate/include/nifty/graph/opt/multicut/multicut_mp.hxx:13,
                 from /home/hanslovskyp/workespace-intellij/paintera/nifty/src/python/lib/graph/opt/multicut/multicut_mp.cxx:3:
/home/hanslovskyp/workespace-intellij/paintera/nifty/externals/LP_MP/include/LP_MP.h: In copy constructor ‘LP_MP::LP_sat<BASE_LP_CLASS>::LP_sat(LP_MP::LP_sat<BASE_LP_CLASS>&)’:
/home/hanslovskyp/workespace-intellij/paintera/nifty/externals/LP_MP/include/LP_MP.h:700:25: error: cannot convert ‘std::vector<int>’ to ‘LGL*’
     sat_var_(lglclone(o.sat_var_)),
                       ~~^~~~~~~~
```

**Comment by constantinpape** [comment]
Just to understand the first issue:
if you do 
`conda install -c conda-forge -c cpape -c ilastik-forge nifty`
you run into the import error?

If so, the issue is that my nifty build links against an older version of the fastfilters library.
There should be an easy fix by specifying a slightly older version.
I will try to check this.

**Comment by hanslovsky** [comment]
Yes, I just ran this:
```shell
conda create -n nifty-test -c conda-forge -c cpape -c ilastik-forge python=3.6 nifty
source activate nifty-test
conda install -c conda-forge boost=1.66.0 boost-cpp=1.66.0
python -c 'import nifty.graph.rag as nrag'
```

This is what I see:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hanslovskyp/miniconda3/envs/nifty-test/lib/python3.6/site-packages/nifty/graph/rag/__init__.py", line 7, in <module>
    from . import _rag as __rag
ImportError: libfastfilters.so.0.2.5-9-geb270d2: cannot open shared object file: No such file or directory
```
So a rebuild might just do the trick (too bad, ilastik-forge does not seem to keep older packages).

**Comment by hanslovsky** [comment]
Regarding my build issues: I was able to build with `WITH_LP_MP=OFF` and without any examples or tests. It seems to work now (I was able to start the solver server but I do not have any client to test, yet).

This is the environment that I built in:
```yaml
name: agglomerate
channels:
  - conda-forge
  - ilastik-forge
  - defaults
dependencies:
  - boost=1.67.0=py36h3e44d54_0
  - boost-cpp=1.67.0=h3a22d5f_0
  - bzip2=1.0.6=h470a237_2
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - h5py=2.8.0=py36hb794570_1
  - hdf5=1.10.2=hc401514_1
  - icu=58.2=hfc679d8_0
  - libsodium=1.0.16=0
  - mkl_fft=1.0.4=py36_0
  - mkl_random=1.0.1=py36_0
  - ncurses=5.9=10
  - openblas=0.2.20=8
  - openssl=1.0.2o=0
  - pip=18.0=py36_0
  - python=3.6.5=1
  - pyyaml=3.12=py36_1
  - pyzmq=17.1.0=py36hae99301_0
  - readline=7.0=0
  - setuptools=40.0.0=py36_0
  - six=1.11.0=py36_1
  - sqlite=3.20.1=2
  - tk=8.6.8=0
  - wheel=0.31.1=py36_0
  - xz=5.2.3=0
  - yaml=0.1.7=0
  - zeromq=4.2.5=hfc679d8_4
  - zlib=1.2.11=h470a237_3
  - blas=1.0=mkl
  - intel-openmp=2018.0.3=0
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - mkl=2018.0.3=1
  - numpy=1.12.1=py36he24570b_1
  - numpy-base=1.14.5=py36hdbf6ddf_4
  - scikit-learn=0.19.1=py36hedc7406_0
  - scipy=1.1.0=py36hc49cb51_0
  - fastfilters=0.2.6.post13=py36_1_gce61889
prefix: /home/hanslovskyp/miniconda3/envs/agglomerate
```

Tests ran successfully, so that seems to work for me, now.

**Comment by constantinpape** [comment]
Yes indeed, the issue is that 0.2.5 is not on ilastik-forge any longer.
I will rebuild  the conda package with current dependencies.

Glad you got the install to work, just in case the options you need are `WITH_FASTFILTERS=ON`, `WITH_HDF5=ON`, the rest shouldn't matter.

**Comment by hanslovsky** [comment]
Cool, thank you.

**Comment by constantinpape** [comment]
I have build and uploaded a new package.
Imports work now and I have also fixed the dependencies (so at least the package will fail to install now if a dependency disappears again).
You can install via 
`conda install -c conda-forge -c cpape -c ilastik-forge nifty`

I have only build a python 3.6 version and only with gcc 7.3.
If you need another python version or get gcc compatability issues, let me know.

**Comment by hanslovsky** [comment]
Unfortunately, nifty cannot be installed together with vigra now:
```shell
$ conda create -n aggl2 -c conda-forge -c cpape -c ilastik-forge python=3.6 pyzmq scikit-learn h5py fastfilters nifty=0.6 vigra
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - nifty=0.6
  - vigra
Use "conda info <package>" to see the dependencies for each package.
```

```shell
conda search -c cpape nifty=0.6 --info
Loading channels: done
nifty 0.6 py36_0_g3ff3b47_stacked_rag
-------------------------------------
file name   : nifty-0.6-py36_0_g3ff3b47_stacked_rag.tar.bz2
name        : nifty
version     : 0.6
build string: py36_0_g3ff3b47_stacked_rag
build number: 0
size        : 2.5 MB
arch        : x86_64
constrains  : ()
platform    : Platform.linux
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/cpape/linux-64/nifty-0.6-py36_0_g3ff3b47_stacked_rag.tar.bz2
md5         : 11c1b48b43377a733a582777ca8bd6fe
dependencies: 
  - boost 1.66.0.*
  - fastfilters 0.2.6.*
  - hdf5 1.8.17.*
  - numpy
  - python >=3.6,<3.7.0a0
  - scikit-image
  - scipy
```

```shell
conda search -c conda-forge vigra=1.11.1=py36_6 --info
Loading channels: done
vigra 1.11.1 py36_6
-------------------
file name   : vigra-1.11.1-py36_6.tar.bz2
name        : vigra
version     : 1.11.1
build string: py36_6
build number: 6
size        : 8.0 MB
arch        : x86_64
constrains  : ()
platform    : Platform.linux
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/vigra-1.11.1-py36_6.tar.bz2
md5         : 09c55f817f954b18baeadc7bfd77bb5b
dependencies: 
  - boost 1.66.0
  - fftw
  - hdf5 1.10.1
  - jpeg 9*
  - libpng >=1.6.32,<1.6.35
  - libtiff >=4.0.8,<4.0.10
  - numpy >=1.8
  - python 3.6*
  - zlib 1.2.11
```
It seems that the hdf5 versions are incompatible. To confirm, create an environment with only nifty and vigra:
```shell
conda create -n vigranifty -c conda-forge -c cpape -c ilastik-forge python=3.6 vigra=1.11.1=py36_6 nifty=0.6
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - nifty=0.6 -> hdf5=1.8.17
  - vigra==1.11.1=py36_6 -> hdf5==1.10.1
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by constantinpape** [comment]
I had pinned the hdf5 version to a relatively old one because that was the vigra dependency at the time.
I have rebuild (and uploaded) with the new dependency, the installation with vigra works now.

**Comment by hanslovsky** [comment]
Just tested and confirmed that it works. Thanks for taking action so quickly @constantinpape
